# Generated by Django 4.2.20 on 2025-04-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='state',
            field=models.TextField(default='{}'),
        ),
    ]
